#!/bin/bash


adb shell input keyevent 67
adb shell input keyevent 67
adb shell input keyevent 67
adb shell input keyevent 67
adb shell input keyevent 67
adb shell input keyevent 67

for i in $(seq 0 10)
  do
  adb shell input keyevent 67
  done
